name: TestWheel

on:
  workflow_dispatch:
    inputs:
      runid:
        description: 'run-id (if empty, downloads from PyPI)'
        default: ''

jobs:
  testwheel:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04, ubuntu-24.04,
             windows-latest,
             macos-13, macos-14, macos-15]
        py: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    name: ${{ matrix.os }} py${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - run: python -m pip install gemmi
        if: ${{ github.event.inputs.runid == '' }}

      - uses: actions/download-artifact@v4
        if: ${{ github.event.inputs.runid != '' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.runid }}
          path: wheels
          merge-multiple: true
      - run: python -m pip install --no-index --find-links=wheels gemmi
        if: ${{ github.event.inputs.runid != '' }}

      - run: python -m unittest discover -s tests -v
