# Use cibuildwheel v2 to build wheels for Python 3.
# Based on https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Wheels2

on:
  workflow_dispatch:
    inputs:
      cibw_build:
        description: 'CIBW_BUILD'
        default: '*'
      cibw_skip:
        description: 'CIBW_SKIP'
        # To limit the number of builds, skip most of musl-based versions,
        # PyPy, and 32-bit builds.
        default: 'pp* cp{38,39,310}-musllinux* *_i686 *-win32'
      cibw_config_settings:
        description: 'CIBW_CONFIG_SETTINGS'
        default: ''

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04-arm, windows-2022, macos-13, macos-14]

    steps:
    - uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v3.0.0
      env:
        CIBW_BUILD: ${{ github.event.inputs.cibw_build }}
        CIBW_SKIP: ${{ github.event.inputs.cibw_skip }}
        CIBW_CONFIG_SETTINGS: ${{ github.event.inputs.cibw_config_settings }}

    - run: ls -lh wheelhouse
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: wheelhouse/*.whl

  merge:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: cibw-wheels
          pattern: cibw-wheels-*
          delete-merged: true
